name: Install and Test
on:
  pull_request:
  workflow_dispatch:

jobs:
  install_and_test:
    strategy:
      fail-fast: false
      matrix:
        python_version:
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'
          - '3.12'
        os:
          - 'ubuntu-latest'
          - 'macos-latest'
    runs-on: ${{ matrix.os }}
    name: Install and test for ${{ matrix.python_version }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}

      - name: Show OS and Python version
        run: |
          python3 -c 'import platform; print("OS: ", platform.platform()); print("Python: ", platform.python_version())'

      - name: Install 'revefi-dbt-client' using setup.py
        run: |
          pip3 install .

      - name: Uninstall 'revefi-dbt-client'
        run: |
          pip3 uninstall -y revefi-dbt-client

      - name: Run unit tests
        run: |
          pip3 install -r requirements-dev.txt
          pytest --verbose