name: Install and Test
on:
  pull_request:
  workflow_dispatch:

jobs:
  install_and_test:
    strategy:
      matrix:
        python_version:
          - 3.8
          - 3.9
          - 3.10
          - 3.11
          - 3.12
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    name: Install and test for ${{ matrix.python_version }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install
        run: |
          python3 -c 'import platform; print(f"OS: {platform.platform()}"); print(f"Python: {platform.python_version()}")'
          pip install git+https://github.com/revefi/dbt_python_client.git
